name: Global Pipeline
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI

jobs:
  everything:
    uses: cert-labs-hq/automations-repo/.github/workflows/universal-orchestrator.yml@55dff9f1d1a2ade50156bb12c1407feb44a952c7
    secrets: inherit