name: Global Pipeline
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI

jobs:
  everything:
    uses: cert-labs-hq/automations-repo/.github/workflows/universal-orchestrator.yml@13da1fe254f45156b7d8c4e86bdc1ef8fd128fcc
    secrets: inherit