name: use action JS
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Run our custom action
      id: versioning # You need an ID to capture outputs
      uses: cert-labs-hq/automations-repo/.github/actions/hello-js@5d6d85d1c99912400cee9b8c1b62a00b8341f5db
      with:
        who-to-greet: 'Cristian External' # This input is defined in action.yml
    
          # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.versioning.outputs.time }}"
