name: use action
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Smart Setup
        # Use the SHA pinned by Dependabot
        uses: cert-labs-hq/automations-repo/.github/actions/smart-setup@f6b3ace73a566dab75651dc3ab62f75ab895c9d0
        with:
          node-version: '24'

      - name: Build
        run: npm run build