name: use action
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # actions/checkout@v4
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run Smart Setup
        # Use the SHA pinned by Dependabot
        uses: cert-labs-hq/automations-repo/.github/actions/setup@841234a2ab0cd482b18c9e36caa189d5bb264c95
        with:
          node-version: '24'

      - name: Build
        run: npm run build