name: use action
on: [workflow_dispatch] # workflow_dispatch allows manual triggers in the UI


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 

    - name: Run our custom action
      id: versioning # You need an ID to capture outputs
      uses: cert-labs-hq/automations-repo/.github/actions/get-version@785e05c54dec33f4dec584a5d9fcbc453ac07d66